version: "3.5"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  app:
    build:
      context: .
    environment:
      DB_HOST: mysql
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    command: tail -f /dev/null

volumes:
  mysql-data:
