name: trilogy

on: [push, pull_request]

jobs:
  trilogy_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.7, 3.0, 3.1, 3.2]
    runs-on: ${{matrix.os}}
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: github
          MYSQL_PASSWORD: github
          MYSQL_DATABASE: composite_primary_keys_unittest
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      BUNDLE_WITHOUT: "db2 oracle sqlserver sqlite postgresql"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Setup database config
        run: cp test/connections/databases.ci.yml test/connections/databases.yml
      - name: Prepare databases
        run: bundle exec rake trilogy:rebuild_database
        env:
          MYSQL_ROOT_PASSWORD: root
      - name: Create user, grant privledges,and flush # workaround to resolve https://github.com/trilogy-libraries/activerecord-trilogy-adapter/issues/64
        run: |
          mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test';" -uMYSQL_USER -pMYSQL_ROOT_PASSWORD
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost' WITH GRANT OPTION;" -uMYSQL_USER -pMYSQL_ROOT_PASSWORD
          mysql -e "FLUSH PRIVILEGES;" -uMYSQL_USER -pMYSQL_ROOT_PASSWORD
      - name: Trilogy test
        run: bundle exec rake trilogy:test
